
float32 x			# local position setpoint in m in NED
float32 y			# local position setpoint in m in NED
float32 z			# local position setpoint in m in NED

float32 vx			# local velocity setpoint in m/s in NED
float32 vy			# local velocity setpoint in m/s in NED
float32 vz			# local velocity setpoint in m/s in NED

float32 yaw	

bool is_loiter_sp
bool is_takeoff_sp
bool is_land_sp
bool is_idle_sp
bool is_local_frame
bool ignore_alt_hold
bool ignore_attitude
bool ignore_position
bool ignore_velocity
