uint64 timestamp

char[4] datastr

int16 local_datax
int16 local_datay

int16 point_datax_1
int16 point_datay_1

int16 point_datax_2
int16 point_datay_2

int16 point_datax_3
int16 point_datay_3

int16 point_datax_4
int16 point_datay_4

int16 point_datax_5
int16 point_datay_5

int16 point_datax_6
int16 point_datay_6

int16 point_datax_7
int16 point_datay_7

int16 point_datax_8
int16 point_datay_8

int16 point_datax_9
int16 point_datay_9

int16 point_datax_10
int16 point_datay_10
bool is_valid

#TOPICS radar_pos
